export const ROLE_DEFAULT_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: ['*'],
  ADMIN: [
    'VIEW_USERS', 'CREATE_USER', 'EDIT_USER', 'DELETE_USER', 'MANAGE_ROLES',
    'VIEW_PROJECTS', 'ALLOCATE_PROJECT', 'VIEW_ASSETS', 'MANAGE_PERMISSIONS'
  ],
  HR: [
    'VIEW_APPLICATIONS', 'UPDATE_APPLICATION_STATUS',
    'VIEW_ASSESSMENTS', 'ASSIGN_ASSESSMENT',
    'VIEW_SELECTED_CANDIDATES', 'VIEW_OFFERS', 'GENERATE_OFFER',
    'VIEW_BGV', 'UPDATE_BGV_STATUS',
    'VIEW_TRAINEES'
  ],
  CANDIDATE: [
    'VIEW_JOBS', 'APPLY_JOB', 'VIEW_OWN_APPLICATIONS', 'VIEW_OWN_OFFERS'
  ]
};
